# Default configuration for monarch. Consider changing these values after installation (~/.monarch/monarch.yaml)
debug: false
loglevel: 2
certfile: monarch.crt # cert file relative to monarch home dir
keyfile: monarch.key
interface: 0.0.0.0
httpport: 8000
httpsport: 4433
installdir: agents
# gitusername:
# gitpat:
ignoreconsolewarnings: false

mysqladdress: 172.20.0.3 # default mysql container address
mysqlusername: root
mysqlpassword: monarch