# Default configuration for monarch. Consider changing these values after installation (~/.monarch/monarch.yaml)
debug: false
loglevel: 2
certfile: monarch-cert.pem # cert file relative to monarch home dir
keyfile: monarch-key.pem
cacert: ca-cert.pem # signing cert and key
cakey: ca-key.pem

interface: 0.0.0.0

httpport: 8000
httpsport: 4433
multiplayerport: 1337

loginendpoint: /login
mainendpoint: /
stageendpoint: /index/{file}

session_timeout_minutes: 60

installdir: agents
# gitusername:
# gitpat:
ignoreconsolewarnings: false

mysqladdress: 172.20.0.3 # default mysql container address
mysqlusername: root
mysqlpassword: monarch