name: Monarch Build Tester
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-test-monarch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        install-script:
          - "./scripts/install-monarch.sh"
          - "./scripts/docker-install-monarch.sh"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Monarch
        continue-on-error: false
        run: bash ./scripts/install-monarch.sh

      - name: Setup Monarch Container
        continue-on-error: false
        run: docker build -t monarch -f docker/builder/Dockerfile .

      - name: Run Monarch tests
        run: go test ./...
      - name: Cleanup
        run: bash ./scripts/uninstall-monarch.sh
