name: Monarch Build Tester
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Monarch
        continue-on-error: false
        run: bash ./scripts/install-monarch.sh

      - name: Run Monarch tests
        run: go test ./...
      - name: Cleanup
        run: bash ./scripts/uninstall-monarch.sh